language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    - jorgelca1205@gmail.com

node_js:
  - '8'
  - '10'

install:
  - yarn

jobs:
  include:
    - stage: dependencies
      script:
        - yarn
    - stage: coveralls
      script:
        - yarn coveralls
    - stage: prettier
      script:
        - yarn prettier
    - stage: lint
      script:
        - yarn lint

branches:
  only: master
